services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: news-api-app
    restart: unless-stopped
    volumes:
      - .:/var/www
    environment:
      - APP_ENV=local
      - APP_DEBUG=true
    depends_on:
      - db
      - redis
    networks:
      - newsnet
    command: >
        sh -c "php artisan migrate:fresh --seed && php-fpm"
        sh -c "chmod -R 775 /var/www/storage && chown -R www-data:www-data /var/www/storage"

  webserver:
    image: nginx:alpine
    container_name: news-api-nginx
    restart: unless-stopped
    ports:
      - "8000:80"
    volumes:
      - .:/var/www
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - newsnet

  db:
    image: mysql:8.0
    container_name: news-api-db
    restart: unless-stopped
    ports:
      - "3307:3306"
    env_file:
      - .env
    environment:
        MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
        MYSQL_DATABASE: ${MYSQL_DATABASE}
        MYSQL_ALLOW_EMPTY_PASSWORD: ${MYSQL_ALLOW_EMPTY_PASSWORD:-no}
    volumes:
      - ./docker/dbdata:/var/lib/mysql
    networks:
      - newsnet

  redis:
    image: redis:alpine
    container_name: news-api-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    networks:
      - newsnet

networks:
  newsnet:
    driver: bridge

volumes:
  dbdata:
