openapi: 3.0.3
info:
  title: News Aggregator API
  description: REST API for a news aggregator using Laravel.
  version: 1.0.0
servers:
  - url: http://localhost:8000/api
    description: Local Dev Server

tags:
  - name: Auth
  - name: Articles
  - name: Preferences
  - name: Feed

paths:
  /register:
    post:
      tags: [Auth]
      summary: Register a new user
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name: { type: string }
                email: { type: string, format: email }
                password: { type: string, format: password }
      responses:
        '201':
          description: User registered
        '422':
          description: Validation error

  /login:
    post:
      tags: [Auth]
      summary: Log in
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email: { type: string, format: email }
                password: { type: string }
      responses:
        '200':
          description: Authenticated with token

  /articles:
    get:
      tags: [Articles]
      summary: Get all new articles
      parameters:
        - in: query
          name: page
          schema: { type: integer }
        - in: query
          name: keyword
          schema: { type: string }
        - in: query
          name: category
          schema: { type: string }
        - in: query
          name: source
          schema: { type: string }
        - in: query
          name: date
          schema: { type: string, format: date }
      responses:
        '200':
          description: Paginated list of news articles

  /articles/{id}:
    get:
      tags: [Articles]
      summary: Get single news article
      parameters:
        - name: id
          in: path
          required: true
          schema: { type: integer }
      responses:
        '200':
          description: Article details
        '404':
          description: Not found

  /user/preferences:
    get:
      tags: [Preferences]
      summary: Get user preferences
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Preferences returned

    post:
      tags: [Preferences]
      summary: Set user preferences
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                categories: { type: array, items: { type: string } }
                sources: { type: array, items: { type: string } }
                authors: { type: array, items: { type: string } }
      responses:
        '200':
          description: Preferences saved

  /user/feed:
    get:
      tags: [Feed]
      summary: Get personalized article feed
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Personalized feed based on user preferences

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
