name: Laravel CI

on:
  push:
    branches: [ main ]

env:
  APP_ENV: testing
  DB_CONNECTION: sqlite
  DB_DATABASE: ':memory:'
  CACHE_DRIVER: array
  SESSION_DRIVER: array
  QUEUE_CONNECTION: sync

jobs:
  laravel-tests:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: news_api
          MYSQL_USER: user
          MYSQL_PASSWORD: password
        ports: ['3306:3306']
        options: >-
          --health-cmd="mysqladmin ping --silent"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3

    steps:
      - uses: actions/checkout@v4

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'
          extensions: mbstring, pdo, mysql, sqlite
          coverage: xdebug

      - name: Copy .env
        run: cp .env.example .env

      - name: Install dependencies
        run: composer install --prefer-dist --no-progress

      - name: Generate key
        run: php artisan key:generate

      - name: Clear config cache
        run: php artisan config:clear

      - name: Run tests
        run: php artisan test --coverage-clover=coverage.xml

      - name: Upload test report
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: coverage.xml

  build-and-push:
    needs: laravel-tests
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'

    steps:
      - uses: actions/checkout@v4

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Docker image
        run: |
          docker build -t ghcr.io/divyamohankashyap/news-api-app:latest .

      - name: Push Docker image
        run: |
          docker push ghcr.io/divyamohankashyap/news-api-app:latest
