name: Laravel CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_DATABASE: news
          MYSQL_ROOT_PASSWORD: ''
          MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping --silent"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5
      docker:
        image: docker:24.0.6
        options: '--privileged'

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Copy .env.testing into container
        run: docker cp .env.testing news-api-app:/var/www/.env

      - name: Wait for MySQL
        run: |
          for i in {1..60}; do
            docker exec news-api-db mysqladmin ping -uroot --password= && break
            sleep 20
          done

      - name: Set up Docker Compose
        run: docker compose -f docker-compose.yml up -d --build

      - name: Clear Laravel cache
        run: docker exec news-api-app php artisan optimize:clear

      - name: Composer install
        run: docker exec news-api-app composer install --no-interaction --prefer-dist --no-scripts

      - name: Run migrations
        run: docker exec news-api-app php artisan migrate --force

      - name: Run PHPUnit tests with coverage
        run: docker exec news-api-app php artisan test --env=testing --coverage-clover=coverage.xml

      - name: Upload Coverage Report
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: coverage.xml
