name: Laravel CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  laravel-tests:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_DATABASE: news
          MYSQL_ROOT_PASSWORD: root
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping --silent"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

      redis:
        image: redis:alpine
        ports:
          - 6379:6379
        options: >-
          --health-cmd="redis-cli ping"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.TOKEN_GITHUB }}

      - name: Pull Laravel App Image
        run: docker pull ghcr.io/divyamohankashyap/news-api-app:latest

      - name: Start Laravel App Container with volume mount
        run: |
          docker run -d --name news-api-app \
            --network host \
            -v ${{ github.workspace }}:/var/www \
            -w /var/www \
            ghcr.io/divyamohankashyap/news-api-app:latest \
            sleep infinity

      - name: Copy .env.testing to .env
        run: cp .env.testing .env

      - name: Wait for DB to be ready
        run: sleep 20

      - name: Install Composer Dependencies (inside container)
        run: docker exec news-api-app composer install --no-interaction --prefer-dist --no-scripts

      - name: Run Laravel Tests
        run: docker exec news-api-app php artisan test --log-junit test-report.xml

      - name: Store Test Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: laravel-test-report
          path: test-report.xml
