name: Laravel CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_DATABASE: news
          MYSQL_ROOT_PASSWORD: root
          MYSQL_ALLOW_EMPTY_PASSWORD: "no"
        ports:
          - 3307:3306
        options: >-
          --health-cmd="mysqladmin ping --silent"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

      docker:
        image: docker:24.0.6
        options: --privileged

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.TOKEN_GITHUB }}

      - name: Pull Laravel App Image
        run: docker pull ghcr.io/divyamohankashyap/news-api-app:latest

      - name: Start Laravel App Container with volume mount
        run: |
          docker run -d --name news-api-app \
            --network host \
            -v ${{ github.workspace }}:/var/www \
            -w /var/www \
            ghcr.io/divyamohankashyap/news-api-app:latest \
            sleep infinity

      - name: Copy .env.testing into container
        run: docker cp .env.testing news-api-app:/var/www/.env

      - name: Check MySQL Connection from Laravel Container
        run: |
          docker exec news-api-app sh -c \
          'apt update && apt install -y mysql-client && mysql -h db -u root -proot -e "SHOW DATABASES;"'

      - name: Wait for MySQL
        run: sleep 20

      - name: Composer install
        run: docker exec news-api-app composer install --no-interaction --prefer-dist --no-scripts

      - name: Clear Laravel caches
        run: |
          docker exec news-api-app php artisan config:clear
          docker exec news-api-app php artisan route:clear
          docker exec news-api-app php artisan view:clear
          docker exec news-api-app php artisan cache:clear

      - name: Run migrations
        run: docker exec news-api-app php artisan migrate --force

      - name: Run PHPUnit tests with coverage
        run: docker exec news-api-app php artisan test --env=testing --coverage-clover=coverage.xml

      - name: Upload Coverage Report
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: coverage.xml
