name: Laravel CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  laravel-tests:
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_DATABASE: news
          MYSQL_ROOT_PASSWORD: root
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping --silent"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image for Laravel app
        run: docker build -t news-api-app .

      - name: Create .env.testing file
        run: |
          cat <<EOF > .env.testing
          APP_NAME=Laravel
          APP_ENV=testing
          APP_KEY=${{ secrets.APP_KEY }}
          APP_DEBUG=true
          APP_URL=http://localhost

          LOG_CHANNEL=stack
          LOG_LEVEL=debug

          DB_CONNECTION=mysql
          DB_HOST=db
          DB_PORT=3306
          DB_DATABASE=${{ secrets.DB_DATABASE }}
          DB_USERNAME=${{ secrets.DB_USERNAME }}
          DB_PASSWORD=${{ secrets.DB_PASSWORD }}

          BROADCAST_DRIVER=log
          CACHE_DRIVER=file
          QUEUE_CONNECTION=sync
          SESSION_DRIVER=file
          SESSION_LIFETIME=120

          REDIS_HOST=redis
          REDIS_PASSWORD=null
          REDIS_PORT=6379
          EOF

      - name: Copy .env.testing to .env
        run: cp .env.testing .env

      - name: Run Docker Compose
        run: |
          docker compose up -d db redis
          docker compose up -d app
          sleep 20 # Give containers time to initialize

      - name: Install Composer Dependencies
        run: composer install --no-interaction --prefer-dist --no-scripts

      - name: Copy vendor into container
        run: docker cp vendor news-api-app:/var/www

      - name: Run Laravel Tests
        run: docker exec news-api-app php artisan test --log-junit test-report.xml

      - name: Store Test Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: laravel-test-report
          path: test-report.xml
