name: Laravel Docker CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  laravel-tests:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.TOKEN_GITHUB }}

    - name: Pull Laravel App Image
      run: docker pull ghcr.io/divyamohankashyap/news-api-app:latest

    - name: Start services using docker-compose
      run: |
        cp .env.testing .env
        docker compose -f docker-compose.yml up -d

    - name: Run PHPUnit tests
      run: |
        docker exec news-api-app php artisan config:cache
        docker exec news-api-app php artisan migrate --force
        docker exec news-api-app php artisan test --log-junit test-report.xml

    - name: Save test report
      uses: actions/upload-artifact@v4
      with:
        name: test-report
        path: test-report.xml

    - name: Stop services
      if: always()
      run: docker compose -f docker-compose.yml down --volumes --remove-orphans
