name: Laravel CI with Docker Compose

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-docker-image:
    name: Build & Cache Laravel Docker Image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Build Docker image from docker-compose
        run: docker compose build

      - name: Save Docker image to tarball
        run: docker save news-api-app -o news-api-app.tar

      - name: Upload Docker image as artifact
        uses: actions/upload-artifact@v3
        with:
          name: laravel-docker-image
          path: news-api-app.tar

  laravel-tests:
    name: Run Laravel Tests
    runs-on: ubuntu-latest
    needs: build-docker-image

    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: laravel
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping --silent"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3

      redis:
        image: redis:alpine
        ports:
          - 6379:6379

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Download Docker image artifact
        uses: actions/download-artifact@v3
        with:
          name: laravel-docker-image

      - name: Load Docker image
        run: docker load -i news-api-app.tar

      - name: Start Docker Compose stack
        run: docker compose up -d

      - name: Wait for services to be ready
        run: |
          echo "Waiting for DB and Redis..."
          sleep 20

      - name: Run Laravel Tests
        run: docker exec news-api-app php artisan test
