name: Laravel CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  laravel-tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Authenticate with GHCR
        run: echo "${{ secrets.TOKEN_GITHUB }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Copy .env.testing to .env
        run: cp .env.testing .env

      - name: Override image in docker-compose
        run: |
          sed -i 's|build:.*|image: ghcr.io/divyamohankashyap/news-api-app:latest|' docker/docker-compose.yml

      - name: Start Laravel + MySQL + Redis
        run: docker compose -f docker/docker-compose.yml up -d --wait

      - name: Run Laravel Migrations
        run: docker compose -f docker/docker-compose.yml exec app php artisan migrate --force

      - name: Run Laravel Tests
        run: docker compose -f docker/docker-compose.yml exec app php artisan test --log-junit test-report.xml

      - name: Upload Test Report
        uses: actions/upload-artifact@v4
        with:
          name: laravel-test-report
          path: test-report.xml
