name: Laravel CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  laravel-tests:
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_DATABASE: news
          MYSQL_ROOT_PASSWORD: root
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping --silent"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    env:
      DB_CONNECTION: mysql
      DB_HOST: 127.0.0.1
      DB_PORT: 3306
      DB_DATABASE: news
      DB_USERNAME: root
      DB_PASSWORD: root
      APP_ENV: testing

    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image for Laravel app
        run: docker build -t news-api-app .

      - name: Run Docker Compose
        run: |
          docker compose up -d db redis
          docker compose up -d app
          sleep 20 # Give containers time to initialize

      - name: Run Artisan Tests
        run: docker exec news-api-app php artisan test --log-junit test-report.xml

      - name: Store Test Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: laravel-test-report
          path: test-report.xml
