name: Laravel CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  laravel-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GHCR
        run: echo "${{ secrets.TOKEN_GITHUB }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Pull prebuilt Docker image
        run: docker pull ghcr.io/divyamohankashyap/news-api-app:latest

      - name: Start DB and Redis Services
        run: |
          docker network create laravel-ci
          docker run -d --rm \
            --name mysql \
            --network laravel-ci \
            -e MYSQL_ROOT_PASSWORD=root \
            -e MYSQL_DATABASE=news \
            -p 3306:3306 \
            mysql:8.0

          docker run -d --rm \
            --name redis \
            --network laravel-ci \
            redis:alpine

          sleep 20 # Allow services to initialize

      - name: Install Composer Dependencies
        run: composer install --no-interaction --prefer-dist --no-scripts

      - name: Copy vendor into container
        run: docker cp vendor news-api-app:/var/www

      - name: Run Laravel Tests in Prebuilt Container
        run: |
          docker run --rm \
            --name app \
            --network laravel-ci \
            -e DB_CONNECTION=mysql \
            -e DB_HOST=mysql \
            -e DB_PORT=3306 \
            -e DB_DATABASE=news \
            -e DB_USERNAME=root \
            -e DB_PASSWORD=root \
            -v ${{ github.workspace }}:/var/www \
            ghcr.io/divyamohankashyap/news-api-app:latest \
            php artisan test --log-junit test-report.xml

      - name: Upload test report
        uses: actions/upload-artifact@v4
        with:
          name: laravel-test-report
          path: test-report.xml
