name: Laravel CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      db:
        image: mysql:8.0
        env:
          MYSQL_DATABASE: news
          MYSQL_ROOT_PASSWORD: root
          MYSQL_ALLOW_EMPTY_PASSWORD: "no"
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping --silent"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=10

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.TOKEN_GITHUB }}

      - name: Pull Laravel App Image
        run: docker pull ghcr.io/divyamohankashyap/news-api-app:latest

      - name: Start Laravel App Container
        run: |
          docker run -d --name news-api-app \
            -v ${{ github.workspace }}:/var/www \
            -w /var/www \
            ghcr.io/divyamohankashyap/news-api-app:latest \
            sleep infinity

      - name: Copy .env.testing into container
        run: docker cp .env.testing $(docker ps -qf "name=app"):/var/www/.env

      - name: Wait for MySQL to be ready
        run: |
          echo "Waiting for DB to be ready..."
          until docker exec $(docker ps -qf "name=app") mysqladmin ping -h"db" --silent; do
            sleep 2
          done

      - name: Composer install
        run: docker exec $(docker ps -qf "name=app") composer install --no-interaction --prefer-dist --no-scripts

      - name: Clear Laravel caches
        run: |
          docker exec $(docker ps -qf "name=app") php artisan config:cache
          docker exec $(docker ps -qf "name=app") php artisan config:clear
          docker exec $(docker ps -qf "name=app") php artisan optimize:clear
          docker exec $(docker ps -qf "name=app") php artisan route:clear
          docker exec $(docker ps -qf "name=app") php artisan view:clear
          docker exec $(docker ps -qf "name=app") php artisan cache:clear

      - name: Run migrations
        run: docker exec $(docker ps -qf "name=app") php artisan migrate --force

      - name: Run PHPUnit tests with coverage
        run: docker exec $(docker ps -qf "name=app") php artisan test --env=testing --coverage-clover=coverage.xml

      - name: Upload Coverage Report
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: coverage.xml
